import React from 'react';
import { FileText, Download, FileSpreadsheet, File } from 'lucide-react';
import InfoTooltip from './InfoTooltip';

interface Props {
  searchQuery: string;
}

const Reports: React.FC<Props> = ({ searchQuery }) => {
  const reports = [
    {
      id: 1,
      title: 'Communications Management Plan',
      process: 'Plan Communications (5.3)',
      date: '2023-10-25',
      type: 'Plan',
      formats: ['PDF', 'DOCX']
    },
    {
      id: 2,
      title: 'Stakeholder Engagement Assessment Matrix',
      process: 'Monitor Engagement (5.6)',
      date: '2023-10-26',
      type: 'Matrix',
      formats: ['PDF', 'CSV']
    },
    {
      id: 3,
      title: 'Communication Performance Report',
      process: 'Monitor Communications (5.7)',
      date: '2023-10-27',
      type: 'Report',
      formats: ['PDF']
    },
    {
      id: 4,
      title: 'Stakeholder Register (v2.1)',
      process: 'Identify Stakeholders',
      date: '2023-10-26',
      type: 'Register',
      formats: ['CSV', 'XLSX']
    },
    {
      id: 5,
      title: 'Issue Log - Communications',
      process: 'Monitor Communications (5.7)',
      date: 'Today',
      type: 'Log',
      formats: ['CSV']
    }
  ];

  const filteredReports = reports.filter(report => 
    report.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    report.process.toLowerCase().includes(searchQuery.toLowerCase()) ||
    report.type.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const handleDownload = (reportTitle: string, format: string) => {
    // Simulation of a download action
    alert(`Downloading "${reportTitle}" in ${format} format...`);
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-gray-800 dark:text-white flex items-center">
            Reports & Outputs
            <InfoTooltip text="Formal documentation generated by PMIS processes." />
          </h2>
          <p className="text-gray-500 dark:text-gray-400 text-sm">Central repository for project management deliverables and artifacts.</p>
        </div>
        <button className="flex items-center gap-2 px-4 py-2 border border-gray-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-gray-700 dark:text-gray-200 rounded-md hover:bg-gray-50 dark:hover:bg-slate-700 shadow-sm transition-colors">
            <Download className="w-4 h-4" />
            Download All
        </button>
      </div>

      <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-100 dark:border-blue-900/30 rounded-lg p-4 flex items-start gap-3">
        <FileText className="w-5 h-5 text-blue-600 dark:text-blue-400 mt-0.5" />
        <div>
            <h4 className="text-sm font-semibold text-blue-800 dark:text-blue-300 mb-1 flex items-center">
                PMBOK® Guide Compliance
                <InfoTooltip text="Adherence to Project Management Body of Knowledge standards." />
            </h4>
            <p className="text-sm text-blue-700 dark:text-blue-200">
                Generated documents use standard templates suitable for direct inclusion in the Project Management Plan.
            </p>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4">
        {filteredReports.map((report) => (
          <div key={report.id} className="bg-white dark:bg-slate-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-slate-700 flex flex-col md:flex-row md:items-center justify-between gap-4 hover:border-indigo-300 dark:hover:border-indigo-700 transition-colors group">
            <div className="flex items-start gap-4">
              <div className="p-3 bg-gray-100 dark:bg-slate-700 rounded-lg text-gray-600 dark:text-gray-300 group-hover:bg-indigo-50 dark:group-hover:bg-indigo-900/30 group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors">
                {report.formats.includes('CSV') || report.formats.includes('XLSX') ? (
                    <FileSpreadsheet className="w-6 h-6" />
                ) : (
                    <File className="w-6 h-6" />
                )}
              </div>
              <div>
                <h3 className="font-semibold text-gray-800 dark:text-gray-100 text-lg">{report.title}</h3>
                <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-gray-500 dark:text-gray-400 mt-1">
                   <span className="font-medium text-gray-600 dark:text-gray-300">{report.process}</span>
                   <span className="hidden md:inline w-1 h-1 bg-gray-300 dark:bg-gray-600 rounded-full"></span>
                   <span>{report.type}</span>
                   <span className="hidden md:inline w-1 h-1 bg-gray-300 dark:bg-gray-600 rounded-full"></span>
                   <span>Generated: {report.date}</span>
                </div>
              </div>
            </div>

            <div className="flex gap-2 pl-14 md:pl-0">
              {report.formats.map((format) => (
                <button 
                  key={format}
                  onClick={() => handleDownload(report.title, format)}
                  className="flex items-center gap-2 px-3 py-2 border border-gray-200 dark:border-slate-600 rounded-md text-sm font-medium text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-slate-700 hover:text-indigo-600 dark:hover:text-indigo-400 hover:border-indigo-200 dark:hover:border-indigo-800 transition-all"
                >
                  <Download className="w-4 h-4" />
                  {format}
                </button>
              ))}
            </div>
          </div>
        ))}
        {filteredReports.length === 0 && (
            <div className="text-center py-10 text-gray-400 dark:text-gray-500">
                <p>No matching reports found.</p>
            </div>
        )}
      </div>
    </div>
  );
};

export default Reports;